Football Form
<br/>
<?php
$Form = $this->footballForm;
$Form->prepare();

$Form->setAttribute("id","__football_form");
$Form->setAttribute("autocomplete","on");
$Form->setAttribute("class","football_form");
?>

<?php echo $this->form()->openTag($Form);  ?>

<label>Sports Name</label>
<?php
$element = $Form->get("sn");
$element->setAttribute("placeholder","Sports Name");
$element->setAttribute("value","Football");
$element->setAttribute("disabled","disabled");
echo $this->formInput($element);
?>
<br/>
<?php
$element = $Form->get("sportId");
$element->setAttribute('value', "1");
echo $this->formInput($element);
 ?>
<label>Stroger Foot</label>
<?php
$element = $Form->get("foot");
$element->setAttribute("placeholder","Stronger Foot");

echo $this->formInput($element);
?>
<br/>
<label>Format Type</label>
<?php
$element = $Form->get("format");
$element->setAttribute("placeholder","Format");

echo $this->formInput($element);
?>
<br/>
<label>Position</label>
<?php
$element = $Form->get("ps1");
$element->setAttribute("placeholder","Position 1");

echo $this->formInput($element);
?>
<br/>
<?php
$element = $Form->get("Create");
$element->setAttribute("value","Create Football Profile");

echo $this->formInput($element);
?>
<?php echo $this->form()->closeTag();  ?>