<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>LinkMySport | Player Profile</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link rel="stylesheet" href="<?php echo BASE_URL; ?>css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>css/main.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>css/main.css">

    <script src="<?php echo BASE_URL; ?>js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->
<div class="wrapper">

        <div class="row">
            <div id="header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="lms-logo text-center">
                                <a href="" class="lms-logo-link">
                                    LinkMySport
                                </a>
                            </div>
                        </div>
                        <?php $authPack = $this->authPack; if($authPack === "0") {?>
                        <div class="col-md-5  col-md-offset-3">
                            <div class="lms-login text-center">
                                <?php
                                echo $this->viewSigninForm;
                                ?>
                            </div>
                        </div>
                        <?php } else { echo "";}?>
                    </div>
                </div>
            </div>
        </div>

    <?php echo $this->content; ?>
    <div class="footer">

    </div>
</div>



<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="<?php echo BASE_URL; ?>js/vendor/jquery-1.10.1.min.js"><\/script>')</script>

<script src="<?php echo BASE_URL; ?>js/vendor/bootstrap.min.js"></script>

<script src="<?php echo BASE_URL; ?>js/plugins.js"></script>
<script src="<?php echo BASE_URL; ?>js/main.js"></script>

<script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src='//www.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
</body>
</html>